<?php
namespace Facepalm\Tests;

use Facepalm\Models\Image;
use Illuminate\Foundation\Testing\DatabaseTransactions;

//class ImageModelTest extends TestCase
//{
//    use DatabaseTransactions;
//
//    /**
//     * Test autogenerated and unchangeable name
//     */
//    public function testNameFieldIsCreated()
//    {
//        $image = new Image();
//        $this->assertNull($image->name);
//        $image->save();
//        $this->assertEquals(1, preg_match('/[a-h0-9]{32}/', $image->name));
//        $generatedName = $image->name;
//        $image->name = '123';
//        $this->assertEquals($generatedName, $image->name);
//    }
//}
